### ISSUE TITLE
Possible issues

### ISSUE THREAD

**Issue by mariosxer** [franciscogarate/pyliferisk#12]
Hi Francisco,

Cheers for the great package! 

I am new to python and I have been using it lately trying to build a tool for recalculating reserves. I came upon some possible issues:

1) In calculating Cx you use the following formula:

def Cx(mt, x):
    """ Return the Cx """   
    return ((1 / (1 + mt.i)) ** (x + 1)) * mt.dx[x] * ((1 + mt.i) ** 0.5)

where the factor (1 + mt.i) ** 0.5, which I assume you as an approximation, is not usually used in the international commutation functions. 

2) In my code I load a set of information for a portfolio of policholders and I do the following:

Here if I set the nt for example to a mortality table called GKM70 straight, the code works         

                nt = Actuarial(nt = GKM70 , i = int_rate[id])

If instead I assign to nt the loaded value from an excel file like below, an error pops up
                nt = Actuarial(nt = mort_table[id] , i = int_rate[id])

Error:
...Continuum\anaconda3\lib\site-packages\pyliferisk\__init__.py", line 109, in __init__
    self.qx = [0.0] * init

TypeError: can't multiply sequence by non-int of type 'str'

Would you know why this might be happening?

**Comment by franciscogarate** [comment]
Hi Marios, thanks for your comments. I'm working on it.

**Comment by franciscogarate** [comment]
Regarding issue 1, next version 1.11 (coming soon) will include your finding.

Regarding issue2, try to use float(int_rate[id]) or int_rate[id].astype(float) if you're using pandas.

Best regards,

**Comment by franciscogarate** [comment]
Hi @mariosxer. Version 1.11 is available, please update to solve issue (pip install pyliferisk -- upgrade)

Regards,
