### ISSUE TITLE
If you want to just have a look at this. 

### ISSUE THREAD

**Issue by snowde** [franciscogarate/pyliferisk#9]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/20309583/40995437-2744627c-6953-11e8-81cf-20388181e4f2.png">

**Comment by franciscogarate** [comment]
Hi snowde, pyliferisk is not yet available for Python 3.6 (Soon it will be).

**Comment by franciscogarate** [comment]
Hi @snowde. I just updated pyliferisk to python 3. Please don't hesitate to feedback me, all comments are wellcome.
cc @anbarief @alecloudenback @FlorianPons @robbie-sp @kaybenleroll
